name: "Reusable Create Release Workflow"
description: "A composite action to create a GitHub release"

inputs:
  tag_name:
    description: "The Git tag name for the release (e.g., v1.0.0)"
    required: true
    default: ""
  release_name:
    description: "The name of the release (e.g., Release v1.0.0)"
    required: true
    default: ""
  release_body:
    description: "The body of the release notes"
    required: false
    default: ""

  env:
    GITHUB_TOKEN:
      description: "The GitHub Personal Access Token for the organization"
      required: true

outputs:
  upload_url:
    description: "The upload URL for the release"
    value: ${{ steps.create_release.outputs.upload_url }}

runs:
  using: "composite"
  steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Create a release via the GitHub REST API
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      with:
        tag_name: ${{ inputs.tag_name }}
        release_name: ${{ inputs.release_name}}
        body: ${{ inputs.release_body }}
        draft: false
        prerelease: false