name: "Publish Docker Image to Both Docker Hub and GHCR"
description: "Build and publish Docker images to both Docker Hub and GitHub Container Registry."

inputs:
  docker_image_name:
    description: "The name of the Docker image to build and publish"
    required: true
    type: string

env:
  DOCKERHUB_USERNAME:
    description: "Docker Hub username for login"
    required: true
  DOCKERHUB_TOKEN:
    description: "Docker Hub token or password for login"
    required: true
  GHCR_TOKEN:
    description: "GitHub token for publishing to GitHub Container Registry"
    required: true

runs:
  using: "composite"
  steps:
    # Step 1: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}

    # Step 3: Build and push the Docker image to Docker Hub
    - name: Build and push Docker image to Docker Hub
      shell: bash
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --push \
          --tag ${{ env.DOCKERHUB_USERNAME }}/${{ inputs.docker_image_name }}:${{ github.sha }} \
          --tag ${{ env.DOCKERHUB_USERNAME }}/${{ inputs.docker_image_name }}:latest \
          .

    # Step 4: Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}

    # Step 5: Build and push the Docker image to GitHub Container Registry
    - name: Build and push Docker image to GHCR
      shell: bash
      run: |
        # Convert variables to lowercase
        REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        IMAGE_NAME=$(echo "${{ inputs.docker_image_name }}" | tr '[:upper:]' '[:lower:]')
        
        # Build and push Docker image
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --push \
          --tag ghcr.io/$REPO_OWNER/$IMAGE_NAME:${{ github.sha }} \
          --tag ghcr.io/$REPO_OWNER/$IMAGE_NAME:latest \
          .
