name: "Reusable Docker Publish Workflow"
description: "Build and publish Docker images to Docker Hub and GitHub Container Registry."

inputs:
  docker_image_name:
    description: "The name of the Docker image to build and publish"
    required: true
    type: string

env:
  DOCKERHUB_USERNAME:
    description: "Docker Hub username for login"
    required: true
  DOCKERHUB_TOKEN:
    description: "Docker Hub token or password for login"
    required: true
  GHCR_TOKEN:
    description: "GitHub token for publishing to GitHub Container Registry"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ inputs.docker_image_name }}:${{ github.sha }} .
        docker tag ${{ env.DOCKERHUB_USERNAME }}/${{ inputs.docker_image_name }}:${{ github.sha }} ${{ env.DOCKERHUB_USERNAME }}/${{ inputs.docker_image_name }}:latest

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ env.DOCKERHUB_USERNAME }}/${{ inputs.docker_image_name }}:${{ github.sha }}
        docker push ${{ env.DOCKERHUB_USERNAME }}/${{ inputs.docker_image_name }}:latest

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ env.GHCR_TOKEN }}

    - name: Tag Docker image for GHCR
      run: |
        IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/${{ inputs.docker_image_name }}"
        docker tag ${{ env.DOCKERHUB_USERNAME }}/${{ inputs.docker_image_name }}:${{ github.sha }} $IMAGE_NAME:${{ github.sha }}
        docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest

    - name: Push Docker image to GitHub Container Registry
      run: |
        IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/${{ inputs.docker_image_name }}"
        docker push $IMAGE_NAME:${{ github.sha }}
        docker push $IMAGE_NAME:latest