name: "Publish Docker Image to GitHub Container Registry"
description: "Build and publish a Docker image to GitHub Container Registry (GHCR)."

inputs:
  docker_image_name:
    description: "The name of the Docker image to build and publish"
    required: true
    type: string

env:
  GHCR_TOKEN:
    description: "GitHub token for publishing to GitHub Container Registry"
    required: true

runs:
  using: "composite"
  steps:
    # Step 1: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 2: Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ env.GHCR_TOKEN }}

    # Step 3: Build and push the Docker image to GitHub Container Registry
    - name: Build and push Docker image to GHCR
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --push \
          --tag ghcr.io/${{ github.repository_owner }}/${{ inputs.docker_image_name }}:${{ github.sha }} \
          --tag ghcr.io/${{ github.repository_owner }}/${{ inputs.docker_image_name }}:latest \
          .