name: Release Workflow

on:
  push:
    tags:
      - 'v*.*.*'  # Match v1.0.0, v1.0.1, etc.
  workflow_dispatch: # Allow manual triggering of workflow

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: ./create-release.yml
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          release_body: 'Release ${{ github.ref }}'
        env:
          ORG_PAT: ${{ secrets.ORG_PAT }}