name: Release Workflow

on:
  push:
    tags:
      - 'v*.*.*'  # Match v1.0.0, v1.0.1, etc.
  workflow_dispatch: # Allow manual triggering of workflow

jobs:
  create-release:
    uses: ./.github/workflows/reusable-create-release.yml
    with:
      tag_name: ${{ github.ref_name }}
      release_name: 'Release ${{ github.ref_name }}'
      release_body: |
        ## What's New
        - Custom release notes for version `${{ github.ref_name }}`
    secrets:
      ORG_PAT: ${{ secrets.ORG_PAT }}

  upload-assets:
    needs: create-release
    uses: ./.github/workflows/reusable-upload-assets.yml
    with:
      tag_name: ${{ github.ref_name }}
      upload_url: ${{ needs.create-release.outputs.release_url }}
      asset_name: 'workflows.zip'
      asset_path: './workflows.zip'
      asset_content_type: 'application/zip'
    secrets:
      ORG_PAT: ${{ secrets.ORG_PAT }}