name: Reusable Publish Release Workflow

on:
  workflow_call:
    inputs:
      tag_name:
        description: 'The Git tag name for the release (e.g., v1.0.0)'
        required: true
        type: string
      release_name:
        description: 'The name of the release (e.g., Release v1.0.0)'
        required: false
        type: string
        default: ''
      release_body:
        description: 'The body of the release notes'
        required: false
        type: string
        default: ''
      asset_path:
        description: 'The path to the asset file to upload'
        required: true
        type: string
      asset_name:
        description: 'The name of the asset file for the release'
        required: true
        type: string
      asset_content_type:
        description: 'The content type of the asset file for the release'
        required: true
        type: string

    secrets:
      ORG_PAT:
        required: true

jobs:
  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Create a release via the GitHub REST API
      - id: create_release
        name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_PAT }}
        with:
          tag_name: ${{ inputs.tag_name }}
          release_name: ${{ inputs.release_name }}
          body: ${{ inputs.release_body }}
          draft: false
          prerelease: false

      # Step 3: Upload the asset to the release
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ inputs.asset_path }}
          asset_name: ${{ inputs.asset_name }}
          asset_content_type: ${{ inputs.asset_content_type }}